/* Binary Search only works on Sorted elements...Uses in Unique value because left child is less than parent and parent is less than right child...

Time Complexity --> log(n)...More efficient than linear search...
*/